# Notebook 6b — Expanded Colorado 15-minute cloud-frequency climatology

Pixelwise cloud frequency over the expanded 104–109°W, 37–41°N domain from the corrected temperature-binned Gothic decision-tree masks. Conditions are combined with **AND within each cloudy tree leaf** and **OR across cloudy leaves**. Every accepted day with at least 132 aligned scans is included; unavailable days are omitted. Intervals are left-inclusive; for example, 18:00 represents `[18:00, 18:15)` UTC.

In [1]:
from pathlib import Path
import numpy as np
import pandas as pd
import calendar
import xarray as xr
import rasterio
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D

CLIM_DIR = Path('/glade/derecho/scratch/cdalden/colorado_goes/climatology_15min')
DEM_PATH = Path('/glade/derecho/scratch/cdalden/colorado_goes/static/SRTMGL3_colorado_5x4.tif')
FIGURE_DIR = Path('/glade/u/home/cdalden/goes_work/analysis/output_06b_cloud_frequency')
FIGURE_DIR.mkdir(exist_ok=True)

def load_month(month):
    path = CLIM_DIR / f'colorado_5x4_cloud_frequency_15min_climatology_month_{month:02d}.nc'
    return xr.open_dataset(path)

with rasterio.open(DEM_PATH) as src:
    dem = src.read(1, masked=True)
    dem_lon = src.transform.c + (np.arange(src.width) + 0.5) * src.transform.a
    dem_lat = src.transform.f + (np.arange(src.height) + 0.5) * src.transform.e
dem = dem[::10, ::10]
dem_lon = dem_lon[::10]
dem_lat = dem_lat[::10]

monthly = {month: load_month(month) for month in range(1, 13)}
for month, ds in monthly.items():
    print(calendar.month_name[month], ds.attrs['source_complete_year_months'])

/tmp/mplconfig is not a writable directory

Matplotlib created a temporary cache directory at /glade/derecho/scratch/cdalden/tmp/matplotlib-4m_uxrjx because there was an issue with the default path (/tmp/mplconfig); it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.

January 2018-01,2019-01,2020-01,2021-01,2022-01,2023-01,2024-01
February 2018-02,2019-02,2020-02,2021-02,2022-02,2023-02,2024-02
March 2017-03,2018-03,2019-03,2020-03,2021-03,2022-03,2023-03,2024-03
April 2017-04,2018-04,2019-04,2020-04,2021-04,2022-04,2023-04,2024-04
May 2017-05,2018-05,2019-05,2020-05,2021-05,2022-05,2023-05,2024-05
June 2017-06,2018-06,2019-06,2020-06,2021-06,2022-06,2023-06,2024-06
July 2017-07,2018-07,2019-07,2020-07,2021-07,2022-07,2023-07,2024-07
August 2017-08,2018-08,2019-08,2020-08,2021-08,2022-08,2023-08,2024-08
September 2017-09,2018-09,2019-09,2020-09,2021-09,2022-09,2023-09,2024-09
October 2017-10,2018-10,2019-10,2020-10,2021-10,2022-10,2023-10,2024-10
November 2017-11,2018-11,2019-11,2020-11,2021-11,2022-11,2023-11,2024-11
December 2017-12,2018-12,2019-12,2020-12,2021-12,2022-12,2023-12,2024-12

## Example: June 18:00–18:15 UTC

Each pixel is the cloudy-observation count divided by its own valid-observation count across all complete Junes.

In [2]:
with load_month(6) as june:
    june_1800 = june.sel(interval=june.interval_start_minute_utc == 18 * 60).squeeze()
    display(pd.DataFrame({
        'source_year_months': [june.attrs['source_complete_year_months']],
        'domain_mean_cloud_frequency': [float(june_1800.cloud_frequency.mean())],
        'maximum_valid_observations_per_pixel': [int(june_1800.valid_observation_count.max())],
    }))

,source_year_months,domain_mean_cloud_frequency,maximum_valid_observations_per_pixel
0,"2017-06,2018-06,2019-06,2020-06,2021-06,2022-0...",0.236273,680

## 17:00–21:00 UTC 15-minute arrays

The panels cover the half-open interval `[17:00,21:00)` UTC: 11:00–14:45 MDT in May and July. Light contours are spaced every 250 m and bold contours every 1,000 m.

In [3]:
PLOT_STARTS_UTC = np.arange(16 * 60, 24 * 60, 15)
CONTOUR_LEVELS_M = np.arange(2000, 4251, 250)
MAJOR_CONTOUR_LEVELS_M = np.arange(2000, 4001, 1000)
SITES = [
    ('Mt. Crested Butte', -106.94356, 38.88347, 's'),
    ('Gothic Mt.', -107.01072, 38.95626, '+'),
    ('Maroon Pk.', -106.98898, 39.07088, '*'),
]

def plot_interval_array(ds, month_name, output_name):
    selected = ds.where(ds.interval_start_minute_utc.isin(PLOT_STARTS_UTC), drop=True)
    vmin, vmax = 0.1, 0.7
    fig, axes = plt.subplots(8, 4, figsize=(15, 27), sharex=True, sharey=True, constrained_layout=True)
    mesh = None
    for ax, index in zip(axes.flat, range(selected.sizes['interval'])):
        field = selected.cloud_frequency.isel(interval=index, latitude=slice(None, None, 4), longitude=slice(None, None, 4))
        start = int(selected.interval_start_minute_utc.isel(interval=index))
        utc_hour, minute = divmod(start, 60)
        mesh = ax.pcolormesh(field.longitude, field.latitude, field, shading='auto', cmap='gist_stern', vmin=vmin, vmax=vmax, rasterized=True)
        ax.contour(dem_lon, dem_lat, dem, levels=CONTOUR_LEVELS_M, colors='0.22', linewidths=0.38, alpha=0.72)
        ax.contour(dem_lon, dem_lat, dem, levels=MAJOR_CONTOUR_LEVELS_M, colors='0.15', linewidths=0.9, alpha=0.9)
        for _, site_lon, site_lat, marker in SITES:
            ax.scatter(site_lon, site_lat, marker=marker, s=46 if marker == 's' else 85, facecolor='white', edgecolor='black', linewidth=0.9, zorder=5)
        ax.set_title(f'{utc_hour:02d}:{minute:02d} UTC', fontsize=10, fontweight='bold')
        ax.set_aspect('equal')
        ax.grid(alpha=0.18, linewidth=0.4)
    for ax in axes[-1, :]: ax.set_xlabel('Longitude')
    for ax in axes[:, 0]: ax.set_ylabel('Latitude')
    years = ds.attrs['source_complete_year_months']
    days = ds.attrs.get('source_accepted_days', 'unknown')
    fig.suptitle(f'Expanded Colorado {month_name} cloud frequency by 15-minute interval, 16:00–24:00 UTC\nAccepted days: {days}; source months: {years}', fontsize=15)
    legend_handles = [
        Line2D([], [], marker=marker, linestyle='None', markerfacecolor='white', markeredgecolor='black', markeredgewidth=1.2, markersize=10 if marker == 's' else 14, label=label)
        for label, _, _, marker in SITES
    ]
    fig.legend(handles=legend_handles, loc='lower left', ncol=1, frameon=True, bbox_to_anchor=(1.0, 0.0), bbox_transform=axes[-1, -1].transAxes, fontsize=14, borderpad=0.8, labelspacing=0.8, handletextpad=0.7)
    cbar = fig.colorbar(mesh, ax=axes, shrink=0.62, pad=0.02, anchor=(0.0, 0.82))
    cbar.set_label('Cloud frequency', fontsize=18, fontweight='bold')
    cbar.ax.tick_params(labelsize=16)
    for tick in cbar.ax.get_yticklabels(): tick.set_fontweight('bold')
    path = FIGURE_DIR / output_name
    fig.savefig(path, dpi=180, bbox_inches='tight')
    plt.close(fig)
    print(f'{path} color limits: {vmin:.1f} to {vmax:.1f}')
    return path

figure_paths = []
for month, ds in monthly.items():
    name = calendar.month_name[month]
    figure_paths.append(plot_interval_array(ds, name, f'colorado_5x4_month_{month:02d}_1600_0000_utc_cloud_frequency.png'))
display(pd.DataFrame({'figure': figure_paths}))

/glade/derecho/scratch/cdalden/tmp/ipykernel_37956/3068571521.py:23: UserWarning: You passed a edgecolor/edgecolors ('black') for an unfilled marker ('+').  Matplotlib is ignoring the edgecolor in favor of the facecolor.  This behavior may change in the future.
  ax.scatter(site_lon, site_lat, marker=marker, s=46 if marker == 's' else 85, facecolor='white', edgecolor='black', linewidth=0.9, zorder=5)

/glade/u/home/cdalden/goes_work/analysis/output_06b_cloud_frequency/colorado_5x4_month_01_1600_0000_utc_cloud_frequency.png color limits: 0.1 to 0.7

/glade/derecho/scratch/cdalden/tmp/ipykernel_37956/3068571521.py:23: UserWarning: You passed a edgecolor/edgecolors ('black') for an unfilled marker ('+').  Matplotlib is ignoring the edgecolor in favor of the facecolor.  This behavior may change in the future.
  ax.scatter(site_lon, site_lat, marker=marker, s=46 if marker == 's' else 85, facecolor='white', edgecolor='black', linewidth=0.9, zorder=5)

/glade/u/home/cdalden/goes_work/analysis/output_06b_cloud_frequency/colorado_5x4_month_02_1600_0000_utc_cloud_frequency.png color limits: 0.1 to 0.7

/glade/derecho/scratch/cdalden/tmp/ipykernel_37956/3068571521.py:23: UserWarning: You passed a edgecolor/edgecolors ('black') for an unfilled marker ('+').  Matplotlib is ignoring the edgecolor in favor of the facecolor.  This behavior may change in the future.
  ax.scatter(site_lon, site_lat, marker=marker, s=46 if marker == 's' else 85, facecolor='white', edgecolor='black', linewidth=0.9, zorder=5)

/glade/u/home/cdalden/goes_work/analysis/output_06b_cloud_frequency/colorado_5x4_month_03_1600_0000_utc_cloud_frequency.png color limits: 0.1 to 0.7

/glade/derecho/scratch/cdalden/tmp/ipykernel_37956/3068571521.py:23: UserWarning: You passed a edgecolor/edgecolors ('black') for an unfilled marker ('+').  Matplotlib is ignoring the edgecolor in favor of the facecolor.  This behavior may change in the future.
  ax.scatter(site_lon, site_lat, marker=marker, s=46 if marker == 's' else 85, facecolor='white', edgecolor='black', linewidth=0.9, zorder=5)

/glade/u/home/cdalden/goes_work/analysis/output_06b_cloud_frequency/colorado_5x4_month_04_1600_0000_utc_cloud_frequency.png color limits: 0.1 to 0.7

/glade/derecho/scratch/cdalden/tmp/ipykernel_37956/3068571521.py:23: UserWarning: You passed a edgecolor/edgecolors ('black') for an unfilled marker ('+').  Matplotlib is ignoring the edgecolor in favor of the facecolor.  This behavior may change in the future.
  ax.scatter(site_lon, site_lat, marker=marker, s=46 if marker == 's' else 85, facecolor='white', edgecolor='black', linewidth=0.9, zorder=5)

/glade/u/home/cdalden/goes_work/analysis/output_06b_cloud_frequency/colorado_5x4_month_05_1600_0000_utc_cloud_frequency.png color limits: 0.1 to 0.7

/glade/derecho/scratch/cdalden/tmp/ipykernel_37956/3068571521.py:23: UserWarning: You passed a edgecolor/edgecolors ('black') for an unfilled marker ('+').  Matplotlib is ignoring the edgecolor in favor of the facecolor.  This behavior may change in the future.
  ax.scatter(site_lon, site_lat, marker=marker, s=46 if marker == 's' else 85, facecolor='white', edgecolor='black', linewidth=0.9, zorder=5)

/glade/u/home/cdalden/goes_work/analysis/output_06b_cloud_frequency/colorado_5x4_month_06_1600_0000_utc_cloud_frequency.png color limits: 0.1 to 0.7

/glade/derecho/scratch/cdalden/tmp/ipykernel_37956/3068571521.py:23: UserWarning: You passed a edgecolor/edgecolors ('black') for an unfilled marker ('+').  Matplotlib is ignoring the edgecolor in favor of the facecolor.  This behavior may change in the future.
  ax.scatter(site_lon, site_lat, marker=marker, s=46 if marker == 's' else 85, facecolor='white', edgecolor='black', linewidth=0.9, zorder=5)

/glade/u/home/cdalden/goes_work/analysis/output_06b_cloud_frequency/colorado_5x4_month_07_1600_0000_utc_cloud_frequency.png color limits: 0.1 to 0.7

/glade/derecho/scratch/cdalden/tmp/ipykernel_37956/3068571521.py:23: UserWarning: You passed a edgecolor/edgecolors ('black') for an unfilled marker ('+').  Matplotlib is ignoring the edgecolor in favor of the facecolor.  This behavior may change in the future.
  ax.scatter(site_lon, site_lat, marker=marker, s=46 if marker == 's' else 85, facecolor='white', edgecolor='black', linewidth=0.9, zorder=5)

/glade/u/home/cdalden/goes_work/analysis/output_06b_cloud_frequency/colorado_5x4_month_08_1600_0000_utc_cloud_frequency.png color limits: 0.1 to 0.7

/glade/derecho/scratch/cdalden/tmp/ipykernel_37956/3068571521.py:23: UserWarning: You passed a edgecolor/edgecolors ('black') for an unfilled marker ('+').  Matplotlib is ignoring the edgecolor in favor of the facecolor.  This behavior may change in the future.
  ax.scatter(site_lon, site_lat, marker=marker, s=46 if marker == 's' else 85, facecolor='white', edgecolor='black', linewidth=0.9, zorder=5)

/glade/u/home/cdalden/goes_work/analysis/output_06b_cloud_frequency/colorado_5x4_month_09_1600_0000_utc_cloud_frequency.png color limits: 0.1 to 0.7

/glade/derecho/scratch/cdalden/tmp/ipykernel_37956/3068571521.py:23: UserWarning: You passed a edgecolor/edgecolors ('black') for an unfilled marker ('+').  Matplotlib is ignoring the edgecolor in favor of the facecolor.  This behavior may change in the future.
  ax.scatter(site_lon, site_lat, marker=marker, s=46 if marker == 's' else 85, facecolor='white', edgecolor='black', linewidth=0.9, zorder=5)

/glade/u/home/cdalden/goes_work/analysis/output_06b_cloud_frequency/colorado_5x4_month_10_1600_0000_utc_cloud_frequency.png color limits: 0.1 to 0.7

/glade/derecho/scratch/cdalden/tmp/ipykernel_37956/3068571521.py:23: UserWarning: You passed a edgecolor/edgecolors ('black') for an unfilled marker ('+').  Matplotlib is ignoring the edgecolor in favor of the facecolor.  This behavior may change in the future.
  ax.scatter(site_lon, site_lat, marker=marker, s=46 if marker == 's' else 85, facecolor='white', edgecolor='black', linewidth=0.9, zorder=5)

/glade/u/home/cdalden/goes_work/analysis/output_06b_cloud_frequency/colorado_5x4_month_11_1600_0000_utc_cloud_frequency.png color limits: 0.1 to 0.7

/glade/derecho/scratch/cdalden/tmp/ipykernel_37956/3068571521.py:23: UserWarning: You passed a edgecolor/edgecolors ('black') for an unfilled marker ('+').  Matplotlib is ignoring the edgecolor in favor of the facecolor.  This behavior may change in the future.
  ax.scatter(site_lon, site_lat, marker=marker, s=46 if marker == 's' else 85, facecolor='white', edgecolor='black', linewidth=0.9, zorder=5)

/glade/u/home/cdalden/goes_work/analysis/output_06b_cloud_frequency/colorado_5x4_month_12_1600_0000_utc_cloud_frequency.png color limits: 0.1 to 0.7

                                               figure
0   /glade/u/home/cdalden/goes_work/analysis/outpu...
1   /glade/u/home/cdalden/goes_work/analysis/outpu...
2   /glade/u/home/cdalden/goes_work/analysis/outpu...
3   /glade/u/home/cdalden/goes_work/analysis/outpu...
4   /glade/u/home/cdalden/goes_work/analysis/outpu...
5   /glade/u/home/cdalden/goes_work/analysis/outpu...
6   /glade/u/home/cdalden/goes_work/analysis/outpu...
7   /glade/u/home/cdalden/goes_work/analysis/outpu...
8   /glade/u/home/cdalden/goes_work/analysis/outpu...
9   /glade/u/home/cdalden/goes_work/analysis/outpu...
10  /glade/u/home/cdalden/goes_work/analysis/outpu...
11  /glade/u/home/cdalden/goes_work/analysis/outpu...